[[plugins]]
repo = 'Shougo/ddc.vim'
depends = [
  'denops.vim',
  'pum.vim',
  'ddc-ui-pum'
  'ddc-nvim-lsp',
  'ddc-around',
  'ddc-file',
  'ddc-emoji',
  'ddc-fuzzy',
  'ddc-source-cmdline-history',
  'ddc-shell-history',
  'ddc-matcher_head',
  'ddc-sorter_rank',
]
on_event = ['InsertEnter', 'CursorHold', 'CmdlineEnter']
hook_source = '''
  execute "source " . g:my_initvim_path . "/plugins/ddc.vim"
'''

# UI ####################

[[plugins]]
repo = 'Shougo/ddc-ui-pum'
depends = ['pum.vim']

# SOURCE ####################

[[plugins]]
repo = 'Shougo/ddc-around'

[[plugins]]
repo = 'Shougo/ddc-nvim-lsp'

[[plugins]]
repo = 'LumaKernel/ddc-file'
on_source = 'ddc.vim'

[[plugins]]
repo = 'gamoutatsumi/ddc-emoji'
on_source = 'ddc.vim'

[[plugins]]
repo = 'tani/ddc-fuzzy'
on_source = 'ddc.vim'

[[plugins]]
repo='Shougo/ddc-source-cmdline-history'
on_source = 'ddc.vim'

[[plugins]]
repo='delphinus/ddc-shell-history'
on_source = 'ddc.vim'

# MATCHER ####################

[[plugins]]
repo = 'Shougo/ddc-matcher_head'
on_source = 'ddc.vim'

# SORTER ####################

[[plugins]]
repo = 'Shougo/ddc-sorter_rank'
on_source = 'ddc.vim'

