[[plugins]]
repo = 'Shougo/ddc.vim'
depends = [
  'denops.vim',
  'pum.vim',
  'ddc-ui-pum'
  'ddc-source-nvim-lsp',
  'ddc-source-around',
  'ddc-buffer',
#  'ddc-dictionary',
  'ddc-source-file',
  'ddc-fuzzy',
  'ddc-cmdline-history',
  'ddc-shell-history',
  'ddc-matcher_head',
  'ddc-source-omni',
#  'ddc-path',
  'ddc-sorter_rank',
  'vim-vsnip',
  'vim-vsnip-integ',

  'ddc-converter_remove_overlap',
  'ddc-converter_truncate',

  'windows-clipboard-history.vim',
]
#on_event = ['VimEnter']
on_event = ['InsertEnter', 'CursorHold']
hook_source = '''
  execute "source " . g:my_initvim_path . "/plugins/ddc.vim"
'''

# UI ####################

[[plugins]]
repo = 'Shougo/ddc-ui-pum'
depends = ['pum.vim']

# SOURCE ####################

[[plugins]]
repo = 'Shougo/ddc-source-around'
on_source = 'ddc.vim'

[[plugins]]
repo = 'matsui54/ddc-buffer'
on_source = 'ddc.vim'

#[[plugins]]
#repo = 'matsui54/ddc-source-dictionary'
#on_source = 'ddc.vim'

[[plugins]]
repo = 'LumaKernel/ddc-source-file'
on_source = 'ddc.vim'

[[plugins]]
repo = 'Shougo/ddc-source-nvim-lsp'
on_source = 'ddc.vim'

[[plugins]]
repo = 'Shougo/ddc-source-omni'
on_source = 'ddc.vim'


#[[plugins]]
#repo = 'tani/ddc-path'
#on_source = 'ddc.vim'

# SOURCE_SHELL ####################

[[plugins]]
repo='Shougo/ddc-cmdline-history'
on_source = 'ddc.vim'

[[plugins]]
repo='delphinus/ddc-shell-history'
on_source = 'ddc.vim'

# MATCHER ####################

[[plugins]]
repo = 'Shougo/ddc-matcher_head'
on_source = 'ddc.vim'

# SORTER ####################

[[plugins]]
repo = 'Shougo/ddc-sorter_rank'
on_source = 'ddc.vim'

[[plugins]]
repo = 'tani/ddc-fuzzy'
on_source = 'ddc.vim'

# CONVERTER ####################

[[plugins]]
repo = 'Shougo/ddc-converter_remove_overlap'
on_source = 'ddc.vim'

[[plugins]]
repo = 'matsui54/ddc-converter_truncate'
on_source = 'ddc.vim'


# SNIPPET ####################

[[plugins]]
repo = 'hrsh7th/vim-vsnip'
depends = ['vim-vsnip-integ', 'friendly-snippets']
on_source = 'ddc.vim'
hook_source = '''
  execute "source " . g:my_initvim_path . "/plugins/ddc.snippets.vim"
'''

[[plugins]]
repo = 'hrsh7th/vim-vsnip-integ'
on_source = 'ddc.vim'

[[plugins]]
repo = 'rafamadriz/friendly-snippets'
on_source = 'ddc.vim'

