[[plugins]] # dein.vimをdein自身で更新させる
repo = 'Shougo/dein.vim'


# hook_add ------------------------------
[[multiple_plugins]]
plugins = [ 'pum.vim', 'vim-choosewin' ]
hook_add = '''
  execute "source " . g:my_initvim_path . "/plugins/base.add.vim"
'''

[[plugins]]
repo = 'Shougo/pum.vim'

[[plugins]]
repo = 't9md/vim-choosewin'


[[plugins]]
repo = 'vim-denops/denops.vim'
hook_add = '''
  let g:denops#deno = "deno"
  function! s:run_deno_server() abort
    !sh -c 'deno run -A --no-lock ./denops/@denops-private/cli.ts'
    let g:denops_server_addr = '127.0.0.1:32123'
  endfunction

  command! RunDenoServer call s:run_deno_server()
  command! Rds RunDenoServer
'''

[[plugins]]
repo = 'kyazdani42/nvim-web-devicons'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'
hook_post_update = '''
  execute "source " . g:my_initvim_path . "/plugins/base.post.update.vim"
'''

