[[plugins]]
repo = 'wsdjeg/dein-ui.vim'
depends = ['dein.vim']
on_event = ['BufEnter']

[[plugins]]
repo = 'iamcco/markdown-preview.nvim'
on_ft = ['markdown', 'pandoc.markdown', 'rmd', 'md']
build = 'sh -c "cd app && yarn install"'

[[plugins]]
repo = 'roxma/vim-hug-neovim-rpc'
on_if = '!has("nvim")'

[[plugins]]
repo = 'roxma/nvim-yarp'
on_if = '!has("nvim")'
build = 'pip install -r requirements.txt'

# completion by [{()}]
[[plugins]]
repo = 'tpope/vim-surround'
on_event = ['BufEnter']

[[plugins]] # カーソル位置のコンテキストのftを判定するライブラリ
repo = 'Shougo/context_filetype.vim'
on_event = ['BufEnter']

[[plugins]] # カーソル位置のコンテキストに合わせてftを切り替える
repo = 'osyo-manga/vim-precious'
depends = ['context_filetype.vim']
on_event = ['BufEnter']

[[plugins]]
repo = 'LeafCage/vimhelpgenerator'
on_ft = ['vimscript', 'lua', 'typescript']

# ddc.vim / ddu.vim ------------------------------
[[plugins]]
repo = 'Milly/windows-clipboard-history.vim'
on_if = 'has("win32")'


[[plugins]]
repo = "Shougo/deol.nvim"
depends = ['pum.vim', 'ddc.vim']
on_event = ['BufEnter']
hook_add = '''
  execute "source " . g:my_initvim_path . "/plugins/lazy.source.vim"
'''

[[plugins]]
repo = 'cohama/lexima.vim'
on_event = ['InsertChange']
hook_post_source = '''
  g:lexima_enable_basic_rules = 1
  g:lexima_enable_newline_rules = 1
  g:lexima_enable_endwise_rules = 1
'''
