[[plugins]]
repo = 'wsdjeg/dein-ui.vim'
depends = ['dein.vim']
on_event = ['BufEnter']

[[plugins]]
repo = 'iamcco/markdown-preview.nvim'
on_ft = ['markdown', 'pandoc.markdown', 'rmd', 'md']
hook_done_update = '''
  if has('win32')
    execute 'pwsh -c "cd app && yarn install"'
  else
    execute 'sh -c "cd app && yarn install"'
  endif
'''
build = ''

[[plugins]]
repo = 'roxma/vim-hug-neovim-rpc'
on_if = '!has("nvim")'

[[plugins]]
repo = 'roxma/nvim-yarp'
on_if = '!has("nvim")'
build = 'pip install -r requirements.txt'

# completion by [{()}]
[[plugins]]
repo = 'tpope/vim-surround'
on_event = ['BufEnter']

[[plugins]] # カーソル位置のコンテキストのftを判定するライブラリ
repo = 'Shougo/context_filetype.vim'
on_event = ['BufEnter']

[[plugins]] # カーソル位置のコンテキストに合わせてftを切り替える
repo = 'osyo-manga/vim-precious'
depends = ['context_filetype.vim']
on_event = ['BufEnter']

[[plugins]]
repo = 'LeafCage/vimhelpgenerator'
on_ft = ['vimscript', 'lua', 'typescript']

# ddc.vim / ddu.vim ------------------------------
[[plugins]]
repo = 'Milly/windows-clipboard-history.vim'
on_if = 'has("win32")'


[[plugins]]
repo = 'cohama/lexima.vim'
on_event = ['InsertChange']
hook_post_source = '''
  g:lexima_enable_basic_rules = 1
  g:lexima_enable_newline_rules = 1
  g:lexima_enable_endwise_rules = 1
'''

[[plugins]]
repo = 'deris/vim-rengbang'
on_event = ['InsertChange']
hook_source = '''
  " Following settings is default value.
  let g:rengbang_default_pattern  = '\(\d\+\)'
  let g:rengbang_default_start    = 0
  let g:rengbang_default_step     = 1
  let g:rengbang_default_usefirst = 0
  let g:rengbang_default_confirm_sequence = [
    \   'pattern',
    \   'start',
    \   'step',
    \   'usefirst',
    \   'format',
    \ ]
'''

[[plugins]]
repo = 'haya14busa/vim-asterisk'
on_event = ['FileReadPost', 'InsertLeave']
hook_source = '''
  let g:asterisk#keeppos = 1
  map *  <Plug>(asterisk-z*)
  map #  <Plug>(asterisk-z#)
  map g* <Plug>(asterisk-gz*)
  map g# <Plug>(asterisk-gz#)
'''

[[plugins]]
repo = 'AndrewRadev/linediff.vim'
on_event = ['FileReadPost', 'InsertChange']

[[plugins]]
repo = 'Pocco81/abbrev-man.nvim'
on_event = ['FileReadPost', 'InsertChange']
lua_source = '''
  local abbrev_man = require("abbrev-man")
  abbrev_man.setup({
    load_natural_dictionaries_at_startup = true,
    load_programming_dictionaries_at_startup = true,
    natural_dictionaries = {
      ["nt_en"] = {}
    },
    programming_dictionaries = {
      ["pr_py"] = {}
    }
  })
'''
