[[plugins]] # dein.vimをdein自身で更新させる
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'vim-denops/denops.vim'
on_event = ['VimEnter']
hook_source = '''
  let g:denops#deno = "deno"
  function! s:run_deno_server() abort
    !sh -c 'deno run -A --no-check ./denops/@denops-private/cli.ts --hostname=0.0.0.0 --port 32123'
    let g:denops_server_addr = '127.0.0.1:32123'
  endfunction

  command! RunDenoServer call s:run_deno_server()
  command! Rds RunDenoServer
  execute "Rds"
'''

[[plugins]]
repo = 'Shougo/pum.vim'
hook_add = '''
  call pum#set_option('max_width', 80)
  call pum#set_option('use_complete', v:true)
  call pum#set_option('border', 'rounded')
'''

[[plugins]]
repo = 'Shougo/vimproc.vim'
#build = 'make'
hook_post_update = '''
  if dein#util#_is_windows()
      let cmd = 'tools\\update-dll-mingw'
  elseif dein#util#_is_cygwin()
      let cmd = 'make -f make_cygwin.mak'
      elseif executable('gmake')
      let cmd = 'gmake'
      else
      let cmd = 'make'
      endif
      let g:dein#plugin.build = cmd
'''

[[plugins]]
repo = 't9md/vim-choosewin'
hook_add = '''
  " invoke with '-'
  nmap  -  <Plug>(choosewin)
'''

