[[plugins]]
repo = 'lewis6991/gitsigns.nvim'
depends = ['vim-fugitive', 'git.nvim']
on_event = ['BufRead']
hook_source = '''
  execute "source " . g:my_initvim_path . "/plugins/git.lua"
'''

[[plugins]]
repo = 'tpope/vim-fugitive'
on_event = ['BufRead']

[[plugins]]
repo = 'dinhhuy258/git.nvim'
on_event = ['BufRead']

