[[plugins]]
repo = 'neovim/nvim-lspconfig'
depends = ['mason.nvim', 'mason-lspconfig.nvim', 'lspsaga.nvim', 'ddc.vim', 'ddc-nvim-lsp', 'denops-popup-preview.vim', 'denops-signature_help']
on_event = ['VimEnter']
hook_source = '''
  execute "source " . g:my_initvim_path . "/plugins/lsp.vim"
'''

[[plugins]]
repo = 'williamboman/mason.nvim'

[[plugins]]
repo = 'williamboman/mason-lspconfig.nvim'

[[plugins]]
repo = 'glepnir/lspsaga.nvim'


[[plugins]]
repo = 'matsui54/denops-popup-preview.vim'

[[plugins]]
repo = 'matsui54/denops-signature_help'
