[[plugins]]
repo = 'neovim/nvim-lspconfig'
depends = ['mason.nvim', 'mason-lspconfig.nvim', 'lspsaga.nvim', 'ddc.vim' 'ddc-nvim-lsp']
on_event = ['BufRead', 'InsertEnter']
hook_source = '''
  execute "source " . g:my_initvim_path . "/plugins/lsp.lua"
'''

[[plugins]]
repo = 'Shougo/ddc-nvim-lsp'

[[plugins]]
repo = 'williamboman/mason.nvim'

[[plugins]]
repo = 'williamboman/mason-lspconfig.nvim'

[[plugins]]
repo = 'glepnir/lspsaga.nvim'

