[[plugins]]
repo = 'nvim-lualine/lualine.nvim'
depends = ['tabline.nvim', 'lualine-lsp-progress', 'nvim-web-devicons', 'bufferline.nvim']
hook_add = '''
  execute "source " . g:my_initvim_path . "/plugins/lualine.lua"
'''

#[[plugins]]
#repo = 'kdheepak/tabline.nvim'

[[plugins]]
repo = 'akinsho/bufferline.nvim'
depends = ['nvim-web-devicons']


[[plugins]]
repo = 'arkav/lualine-lsp-progress'

[[plugins]]
repo = 'kyazdani42/nvim-web-devicons'

