# colorscheme plugins

[[plugins]]
repo = 'cocopon/iceberg.vim'
merged = 0

[[plugins]] 
repo = 'jdkanani/vim-material-theme'
merged = 0

[[plugins]] 
repo = 'sonph/onehalf'
rtp = 'vim'
merged = 0

[[plugins]] 
repo = 'ciaranm/inkpot'
merged = 0

[[plugins]]
repo = 'vim-airline/vim-airline'
depends = ['vim-airline-themes']
hook_add = '''   
  set laststatus=2

  let g:airline_experimental = 1
  let g:airline_detect_spell=1
  let g:airline_powerline_fonts = 1
  let g:airline#extensions#tabline#enabled = 1
  let g:airline#extensions#tabline#buffer_idx_mode = 1
  let g:airline#extensions#virtualenv#enabled = 1

  if !exists('g:airline_symbols')
      let g:airline_symbols = {}
  endif

  " From: https://vi.stackexchange.com/a/3363
  " unicode symbols
  let g:airline_left_sep = '»'
  let g:airline_left_sep = '▶'
  let g:airline_right_sep = '«'
  let g:airline_right_sep = '◀'
  let g:airline_symbols.linenr = '␊'
  let g:airline_symbols.linenr = '␤'
  let g:airline_symbols.linenr = '¶'
  let g:airline_symbols.branch = '⎇'
  let g:airline_symbols.paste = 'ρ'
  let g:airline_symbols.paste = 'Þ'
  let g:airline_symbols.paste = '∥'
  let g:airline_symbols.whitespace = 'Ξ'

  " airline symbols
  let g:airline_left_sep = ''
  let g:airline_left_alt_sep = ''
  let g:airline_right_sep = ''
  let g:airline_right_alt_sep = ''
  let g:airline_symbols.branch = ''
  let g:airline_symbols.readonly = ''
  let g:airline_symbols.linenr = ''
'''

[[plugins]]
repo = 'vim-airline/vim-airline-themes'
