return function(_, _)
--  -- null-ls.nvim
--  --
--  local null_ls = require("null-ls")
--  local sources = { null_ls.builtins.diagnostics.textlint.with({ filetypes = { "markdown" } }) }
--  null_ls.setup({
--    border = 'single',
--    diagnostics_format = '#{m} (#{s}: #{c})',
--    sources = sources,
--  })

--
--  https://github.com/jose-elias-alvarez/null-ls.nvim
--  local null_ls = require("null-ls")
--
--  local code_actions = null_ls.builtins.code_actions
--  local completion = null_ls.builtins.completion
--  local diagnostics = null_ls.builtins.diagnostics
--  local formatting = null_ls.builtins.formatting
--  --local hover = null_ls.builtins.hover
--
--  local sources = {
--    code_actions.gitsigns,
--    completion.vsnip,
--    formatting.stylua,
--    formatting.taplo,
--    diagnostics.textlint.with({
--      filetypes = { 'markdown' },
--      prefer_local = 'node_modules/.bin',
--    }),
--    formatting.textlint.with({
--      filetypes = { 'markdown' },
--      prefer_local = 'node_modules/.bin',
--    }),
--    diagnostics.textlint.credo,
--  }
--
--  null_ls.setup({
--    border = 'single',
--    diagnostics_format = '#{m} (#{s}: #{c})',
--    sources = sources,
--  })
--  null_ls.setup({
--    sources = {
--      null_ls.builtins.formatting.stylua,
--      null_ls.builtins.diagnostics.eslint,
--      null_ls.builtins.completion.spell,
--    },
--    diagnostics_format = "#{m} (#{s}: #{c})",
--  })
end