--local g = vim.g
--local fn = vim.fn
--local uv = vim.uv
--local api = vim.api
--local opt = vim.opt
--local keymap = vim.keymap
--
--local myWinPick = require("plugins.plugin.config.winpick")
--local utils = require("utils")
--
--local myDenops = require("plugins.plugin.config.denops")
--
return {
--  {
--    'keaising/im-select.nvim',
--    config = function()
--      require('im_select').setup {
--      }
--    end
--  }
}
