-- ---------------------------------------------------------------------------
-- TREESITTER CONFIGS
-- ---------------------------------------------------------------------------

return {
--  {
--    lazy = true,
--    'nvim-treesitter/nvim-treesitter',
--    event = { "FileReadPost", "VeryLazy" },
--    build = ":TSUpdate",
--    opts = {
--      ensure_installed = {
--        "lua",
--        "vim",
--        "bash",
--        "blade",
--      },
--
--      sync_install = false,
--
--      highlight = {
--        enable = true,
--        additional_vim_regex_highlighting = false,
--      },
--
--      --indent = {
--      --  enable = true,
--      --},
--    },
--    config = function()
--      --require("nvim-treesitter").setup(opts)
--      require("nvim-treesitter").setup()
--      vim.api.nvim_create_autocmd("FileType", {
--        group = vim.api.nvim_create_augroup("vim-treesitter-start", {}),
--        callback = function(ctx)
--          -- 必要に応じて`ctx.match`に入っているファイルタイプの値に応じて挙動を制御
--          -- `pcall`でエラーを無視することでパーサーやクエリがあるか気にしなくてすむ
--          pcall(vim.treesitter.start)
--        end,
--      })
--    end,
--  },
}

